### ISSUE TITLE
Contribute buildroot supprt for MicroHs?

### ISSUE THREAD

**Issue by emdash** [augustss/MicroHs#10]
Buildroot is a framework for creating small linux systems. At this time, I'm not aware of any any ML-family language in the buildroot package set -- so users looking to experiment with incorporating such code into their systems are on their own.

Since MicroHs can bootstrap itself, it seems like it might be quite easy to get up and running on build-root, compared with alternatives. For reference, this is the current set of packages in buildroot: https://git.busybox.net/buildroot/tree/package.

I might be willing to look into this, after the holidays, if you favor the idea.

**Comment by augustss** [comment]
That sounds like a great idea. I'm happy to accept changes to support buildroot.
