### ISSUE TITLE
Tabs not accepted

### ISSUE THREAD

**Issue by ysangkok** [augustss/MicroHs#12]
I am trying to compile some old Haskell programs from Bird/Wadler and they have tabs. It seems like MicroHs doesn't tolerate this. Not sure it's intentional or not, but I thought I'd bring it up.

```
 % hd Example.hs 
00000000  6d 6f 64 75 6c 65 20 45  78 61 6d 70 6c 65 28 6d  |module Example(m|
00000010  61 69 6e 29 20 77 68 65  72 65 0a 69 6d 70 6f 72  |ain) where.impor|
00000020  74 20 50 72 65 6c 75 64  65 0a 0a 6d 61 69 6e 20  |t Prelude..main |
00000030  3a 3a 20 49 4f 20 28 29  0a 6d 61 69 6e 20 3d 20  |:: IO ().main = |
00000040  64 6f 0a 09 70 75 74 53  74 72 4c 6e 20 22 48 65  |do..putStrLn "He|
00000050  6c 6c 6f 20 57 6f 72 6c  64 22 0a                 |llo World".|
```

```
 % ./bin/mhs -r Example
ERR: mhs: "./Example.hs": line 6, col 1:
  found:    TBrace
  expected: {
```

GHC accepts this.

**Comment by augustss** [comment]
It is intentional, because I don't think tabs are a good idea.
But maybe I'll add it, since it's easy.

**Comment by augustss** [comment]
Done

**Comment by ysangkok** [comment]
Thank you very much, much appreciated. I was unsure whether it should be reported because I do realize that you're trying to clean up some warts of the language, by e.g. requiring export lists.
