### ISSUE TITLE
Forall in type synonym

### ISSUE THREAD

**Issue by ysangkok** [augustss/MicroHs#13]
I am not so knowledgeable in type theory. But I thought type synonyms should be completely transparent. But if they were, then surely this should compile (from the JHC test suite):

```
module Forall (id2) where

-- forall in type synonym
type IdentityFunc = forall a . a -> a

-- type synonym with forall
id2 :: IdentityFunc
id2 x = x
```

But I get:

```
line 8, col 5: Cannot satisfy constraint: (forall (a::a3) . (a -> a) ~ (a8 -> a8))
```

It does compile with GHC .

**Comment by augustss** [comment]
That type synonym is not allowed in Haskell 2010.
That said, it is a reasonable thing to want.  And I thought it would work.  I'll investigate why it doesn't.

**Comment by augustss** [comment]
Fixed
