### ISSUE TITLE
Floats all over the shop

### ISSUE THREAD

**Issue by gergoerdi** [augustss/MicroHs#15]
Targeting a platform with `WANT_FLOAT` turned off, the C compilation step fails due to `parse_double` missing. Seemingly this is easy enough to fix -- we can just gate the `'&'` primop behind `WANT_FLOAT`.

However, if I try that, I quickly discover that the combinator output contains quite a lot of double constants. Even for the empty program `main = pure ()`, there's a small handful of `0.0` and `1.0` constants. Where are these coming from? And how do I get rid of them?

**Comment by gergoerdi** [comment]
Oh and these are not even just noise, something really is using these floats at runtime -- changing `''&'`'s evaluator to just push a `mkFlt(0)` makes the trivial program `main = someExternallyObservableFFI 1` not get to actually calling the FFI function.

**Comment by augustss** [comment]
It now compiles with WANT_FLOAT=0.

Unfortunately, the compiler generates a lot of stuff that is never used (like all of Prelude).
There is a way to get rid of this:
```
bin/mhseval +RTS -rin.comb -oout.comb
```
This will read `in.comb`, do a GC, and write out what's left to `out.comb`.  This must be done with an `mhseval` that supports float.  The resulting combinator file can then be use without float support.
```
~/MicroHs$ bin/mhs Example
~/MicroHs$ bin/mhseval +RTS -rout.comb -oopt.comb
~/MicroHs$ bin/mhseval-nofloat +RTS -ropt.comb
Some factorials
[1,2,6,3628800]
~/MicroHs$
```
This `out.comb` can be turned into a C file by using `Tools/Addcomb`.

This whole thing is not ideal, but it will have to do for now.
