### ISSUE TITLE
KindSignature on EmptyDataDecl

### ISSUE THREAD

**Issue by ysangkok** [augustss/MicroHs#19]
Program:
```
module Example (main) where
import Prelude
import Data.Kind (Type)

main :: IO ()
main = pure ()
data SameKind :: Type
```

Fails with MicroHs:
```
ERR: mhs: "./Example.hs": line 7, col 15:
  found:    ::
  expected: LIdent ( = deriving ; }
```

Succeeds with GHC:
```
ghc Example.hs -XHaskell98 -XKindSignatures -XEmptyDataDecls
```

This is unexpected since these extensions are listed as supported.

**Comment by augustss** [comment]
I believe that MicroHs implements everything mention in [Explicitly-kinded quantification](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/kind_signatures.html).
GHC also accepts what you are trying tp do, but I'm not going to implement that.  Instead MicroHs allows `StandaloneKindSignatures`.

**Comment by augustss** [comment]
I simply forgot to list. 🙂
