### ISSUE TITLE
Records not supported?

### ISSUE THREAD

**Issue by ysangkok** [augustss/MicroHs#3]
If records are not supported, I think that would be worth mentioning in the README.

This is what I tried:

```
module Record (R(..)) where

data R = R1 { r1Field :: () }
```

The error is

```
mhs: "./Record.hs": line 3, col 13:
  found:    {
  expected: LQIdent ( UQIdent [ literal :: => ! | deriving ; }
```

`MicroHs, version 0.8.1.0, combinator file version v5.1`

**Comment by augustss** [comment]
Sorry, no records yet.  I'll update the README.

**Comment by augustss** [comment]
I've implemented records now.
