### ISSUE TITLE
Different runtime support at build time

### ISSUE THREAD

**Issue by yobson** [augustss/MicroHs#39]
This may be a misunderstanding about how the compiler is meant to be used,

But looking at the code in Main.hs, it always loads the `eval-unix-_.h` file and passes this to the C compiler. It also gets the word size from the host instead of the target.

My two questions are
- Would this not break on 32 bit systems? Or other systems which don't use the unix runtime?
- Does this mean that cross compiling with only mhs is currently not possible?

Depending on your answers, I can patch it myself

**Comment by augustss** [comment]
You are right, it is not set up for easy cross compilation.
When I have compiled for micro-controllers, I let MHS generate a .c (not a binary) file, and then I compile that by hand with the right C compiler and configuration file. 
It shouldn't be too hard to make that configurable.

**Comment by yobson** [comment]
I will make that configurable. I have a plan. I'll pass in a default as a preprocessor define and then expose `MHSCONF` as an environment variable. It looks like this is the only part of the compiler that cares about word size and these files in general.

**Comment by augustss** [comment]
That would be great.

The word size is used very little. In the C code it just determines which C type (double or float) is used for Haskell type FloatW.
MHS only supports floating point numbers with the word size of the machine. 

In the Haskell libraries the word size is determined at runtime and used to select the right code (there's very little overhead doing this).

**Comment by augustss** [comment]
Have you seen that you can change the compilation command entirely by setting MHSCC?
That string will be used with $IN and $OUT changed to the input and output files.

**Comment by yobson** [comment]
Ah! That's what it does. I might have a play. First I'm going to work on my patch. Just sat down to make it

**Comment by yobson** [comment]
I've realised that my plan doesn't work as intended. I can't use CPP to hard code the default into the binary because that would affect the generated c distribution. I'll just add the MHS_CONF environment variable for now

**Comment by augustss** [comment]
Merged fixes by yobson
