### ISSUE TITLE
Using cabal packages, dependencies for users 

### ISSUE THREAD

**Issue by ysangkok** [augustss/MicroHs#42]
I am pondering what would be a minimal way to enable using cabal packages from hackage.

Let's assume that PackageImports aren't needed, i.e. each module exists only in one package. And let's assume that versions bounds don't exist, i.e. the latest version always works. 

Let's say our target package depends on foo and bar, which are on hackage. Would it work to just to 'cabal get' those packages and move them to the same source tree? It would be cumbersome to identify the source directory of the library component without using the Cabal library which I would like to avoid.

One could use the topologically sorted build plan (e.g. the output of cabal-plan) from hackage (should be available since docs are built for most?) to find the list of dependencies with their versions, and then a solver could be avoided . If the build plan for bar mentions a package that is in foo too, one could obviously skip extracting it into the source tree.

But, if the plan mentions a different version, one would have to fail the build. If there are too many failures one could use stackage to ensure that the deps of foo and bar are compatible. But then where would the build plan come from? I don't think stackage publishes this.

Maybe i am making this way too hard, and there is a way to just use cabal-install with microHs? Or maybe there is a way to easily get the `-I` include path given just given `build-depends: foo, bar`? 

Would be curious to hear if anyone has thoughts on using microHs with multiple packages.

**Comment by augustss** [comment]
MicroCabal (mcabal) handles most of these things. There is a notion of packages now. 
It's not streamlined yet, but it works for some simple examples.

**Comment by ysangkok** [comment]
Oh, perfect! I hadn't noticed that package. I'll close this then. Link to hackage: https://hackage.haskell.org/package/MicroCabal
