### ISSUE TITLE
Constraint on class method doesn't propagate to instance

### ISSUE THREAD

**Issue by ysangkok** [augustss/MicroHs#44]
This module compiles with GHC, but not with MicroHs. I think it seems like it should compile, so I am reporting this bug.

```
% mhs Main
mhs: "./Main.hs": line 5, col 33: Cannot satisfy constraint: (Eq a#44)
% ghc -fforce-recomp Main.hs
[1 of 2] Compiling Main             ( Main.hs, Main.o )
[2 of 2] Linking Main [Objects changed]
```

The contents of `Main.hs` (taken from transformers-0.4.3.0):

```
-- | Lifting of the 'Eq' class to unary type constructors.
class Eq1 f where
    eq1 :: (Eq a) => f a -> f a -> Bool

instance Eq1 Maybe where eq1 = (==)

main = pure()
```

**Comment by augustss** [comment]
Yeah, that looks like a bug.

**Comment by augustss** [comment]
I've found the bug.  I think the best way to fix it is to do a bigger change to the type checker.
This is a change I've been contemplating already, but I had no pressing reason to do it.
The change is to make all type bound type variables be unique.
It'll be a little while before I have time to do it.

**Comment by augustss** [comment]
I fixed it in a different way.

**Comment by augustss** [comment]
Done
