### ISSUE TITLE
Type roles vs. type classes

### ISSUE THREAD

**Issue by amigalemming** [augustss/MicroHs#46]
I remember a blog post of you (but cannot find it anymore) where you show how some modern hacks in GHC could have been avoided with proper use of type classes. I remember you showed a way to avoid type roles. Are you planning to implement this for MicroHs?

**Comment by augustss** [comment]
Hmmm, I can't remember what I had in mind. If you find my blog post, let me know. 

As it is, there is no need for roles since there is no coercion of newtypes.

**Comment by amigalemming** [comment]
On Sat, 6 Jul 2024, Lennart Augustsson wrote:

> Hmmm, I can't remember what I had in mind. If you find my blog post, let me know.

I assume it was this one:

http://augustss.blogspot.com/2014/12/its-time-for-some-more-haskell-opinions.html

**Comment by augustss** [comment]
Ah yes. I might implement something along those lines.
