### ISSUE TITLE
[0.9.11.0] mhs: error: boot module not found: Data.Typeable

### ISSUE THREAD

**Issue by juhp** [augustss/MicroHs#51]
Maybe something changed between 0.9.8.0 and 0.9.11.0?

When I build 0.9.11.0 today I ran into
```
+ cd MicroHs-0.9.11.0
+ make bootstrap
echo [default]           > targets.conf
echo cc = \"gcc\"     >> targets.conf
echo conf = \"unix-64\" >> targets.conf
gcc -Wall -O3 -Isrc/runtime src/runtime/eval-unix-64.c -lm generated/mhs.c -o bin/mhs
*** Build stage1 compiler, using bin/mhs
bin/mhs -z -i -isrc -ilib -ilib/simple-readline MicroHs.Main -ogenerated/mhs-stage1.c
mhs: error: boot module not found: Data.Typeable
make: *** [Makefile:87: bin/mhs-stage1] Error 1
```
or likely I missed a note about changes to the buildsystem

Logs are available at https://download.copr.fedorainfracloud.org/results/petersen/MicroHs/fedora-rawhide-x86_64/07740545-MicroHs/

**Comment by augustss** [comment]
My fault.  The -boot files were missing from the Hackage distribution.
I've published a new version.
