### ISSUE TITLE
Correct type signature prevents compilation

### ISSUE THREAD

**Issue by ysangkok** [augustss/MicroHs#54]
The following snippet uses language extensions chosen to mimic what MicroHs has:

```
{-# LANGUAGE ScopedTypeVariables, NoFieldSelectors, InstanceSigs #-}
module Identity where

newtype IdentityT f a = IdentityT { runIdentityT :: f a }

instance Functor m => Functor (IdentityT m) where
    fmap f (IdentityT m) = IdentityT (fmap f m)

instance Applicative m => Applicative (IdentityT m) where
    pure x = IdentityT (pure x)
    IdentityT a <*> IdentityT b = IdentityT (a <*> b)

instance Monad m => Monad (IdentityT m) where
    (>>=) :: forall a b. IdentityT m a -> (a -> IdentityT m b) -> IdentityT m b
    IdentityT m >>= k =
      let
        f :: a -> m b
        f x =
          let IdentityT ran = k x
           in ran
      in
      IdentityT (f =<< m)

main :: IO ()
main = pure()
```

Compilation succeeds with GHC: `ghc -c Identity.hs -XHaskell98 -fforce-recomp`

But with MicroHs, it fails: 

```
mhs: "./Identity.hs": line 20, col 15: Cannot satisfy constraint: (b#185 ~ b)
```

If I remove the type signature for `f`, it compiles.

**Comment by ysangkok** [comment]
I thought it might be because the `m` isn't forall'd. But adding it doesn't seem to fix it. So that's why I thought it was worth reporting.

**Comment by ysangkok** [comment]
Ah, the problem is still there if the m is explicitly scoped using `instance forall m. Monad m => Monad (IdentityT m) where`. So surely there must be some bug in MicroHs here. Surely if everything is explicitly scoped and it compiles with GHC, it should compile with MicroHs. I would understand if MicroHs didn't support implicit quantification.

**Comment by augustss** [comment]
Thanks for the report.
MicroHs does not support InstanceSigs.  You'll now get an error message. e8d39154af88f3c63166e7686d2fb91e42386e0a
