### ISSUE TITLE
Irrefutable match on unit requires MonadFail

### ISSUE THREAD

**Issue by ysangkok** [augustss/MicroHs#55]
```
{-# LANGUAGE Haskell98 #-}
module IrrefutableUnit where

irrefutableUnit :: Monad m => m ()
irrefutableUnit = do
  -- Compiles if bind notation is used:
  --   pure () >>= \(~()) -> pure ()
  ~() <- pure ()
  pure ()

main :: IO ()
main = irrefutableUnit
```

results in

```
mhs: "./IrrefutableUnit.hs": line 8, col 4: Cannot satisfy constraint: (MonadFail m)
```

My actual use case has tuples, which shouldn't require MonadFail either. This runs with `runhaskell` on GHC 9.10.1.

**Comment by augustss** [comment]
Thanks for the report.  There were many little problems with irrefutable patterns, but I think it's up to spec now.
Fixed in 9d767b734a2204aa7a9de0f8ba7b0a2b428bfbf0
