### ISSUE TITLE
Support {-# LANGUAGE LambdaCase #-}

### ISSUE THREAD

**Issue by Bodigrim** [augustss/MicroHs#58]
Thanks for this exciting project!

@augustss I heard your answer at ICFP ;) but I'm not quite sure about its exact meaning. Was it a definitive "no, never" or would you accept a PR if someone else implements it?

I tried MicroHs for some of libraries I maintain, and it almost works except `{-# LANGUAGE LambdaCase #-}`. It would be a pity to reduce compatibility because of a purely syntactic extension. Note that `LambdaCase` is a part of [`GHC2024`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/control.html#extension-GHC2024) extension set, so one could expect it to become even more widespread and ubiquitous in the future.

**Comment by augustss** [comment]
The answer was a bit of a joke. I do dislike the concrete syntax of LambdaCase, but not the idea. In fact, the abstract syntax already has it.

So there will be LambdaCase sooner or later. I'll be happy to take a patch.

**Comment by augustss** [comment]
It should be a pure parser change.

**Comment by augustss** [comment]
I implemented LambdaCase.

**Comment by Bodigrim** [comment]
Thanks a lot!
