### ISSUE TITLE
[BUG] layout issue

### ISSUE THREAD

**Issue by Rewbert** [augustss/MicroHs#62]
Hej! I've found a small bug (with hopefully an equally small fix!).

it seems as if the last token in a file is a single-line comment, the layout resolver will throw an error `mhs: error: layoutLS`.

Steps to reproduce:
* Clone the repo
* Add `-- hello I am a comment` at the very bottom of `Example.hs`
```haskell
module Example(fac, main) where

fac :: Int -> Int
fac 0 = 1
fac n = n * fac(n - 1)

main :: IO ()
main = do
  let rs = map fac [1,2,3,10]
  putStrLn "Some factorials"
  print rs

-- hello I am a comment
```
* Run `./bin/mhs Example.hs`
* Observer `mhs: error: layoutLS`

If I add anything after the comment, e.g. a newline, everything works as expected. It also seem to work as expected if it is a multiline comment `{-- hello I am a comment --}`.

I've tried rebuilding the compiler with `./bin/mhs src/MicroHs/Main.hs -i -imhs -isrc -ilib -ipaths -oexe`, but the compiled `exe` throws the same error.

**Comment by augustss** [comment]
Try now. I can't, I'm doing the fix from my phone.

**Comment by Rewbert** [comment]
It works now. I can't believe you're patching bugs from your phone
