### ISSUE TITLE
Importing unit data constructor

### ISSUE THREAD

**Issue by thielema** [augustss/MicroHs#66]
I want to hide Prelude in order to define names that clash with those from Prelude.
But I need unit type `()` and its data constructor `()`.
Thus I import:
~~~~
import qualified Prelude as P
import Prelude (id, (.), ()(()))
~~~~
This yields a parser error on the closing parenthesis.

**Comment by augustss** [comment]
Fixzed in ae797cf0263113d76fd53bd8c8c58f688d14ef1e
