### ISSUE TITLE
Qualified exports

### ISSUE THREAD

**Issue by thielema** [augustss/MicroHs#67]
In [Data.Bool.HT](https://hackage.haskell.org/package/utility-ht-0.0.17.2/src/src/Data/Bool/HT.hs) I re-export identifiers like so:
~~~~
module Data.Bool.HT (
   B.if',
   B.ifThenElse,
   B.select,
   (B.?:),
   B.implies,
   ) where

import qualified Data.Bool.HT.Private as B
~~~~

On import however, I cannot write
~~~~
import Data.Bool.HT.Private (ifThenElse)
~~~~
but have to write
~~~~
import Data.Bool.HT.Private (B.ifThenElse)
~~~~
and I have to write `B.ifThenElse` on call sites.

**Comment by augustss** [comment]
Fixed in e83058f4c2c0fa30fc8737a68ed9309a66e038dc
