### ISSUE TITLE
Compiler identification macro

### ISSUE THREAD

**Issue by treeowl** [augustss/MicroHs#69]
Is there anything like the `__GLASGOW_HASKELL__` or `MIN_VERSION_GLASGOW_HASKELL` macro to detect when we're running on `MicroHs`? `containers` will likely be using some GADTy stuff to optimize sequence folds, and it might be interesting to see how that goes on this system too (though the lack of anything like pattern synonyms or a safe coercion mechanism will likely to limit the benefits).

**Comment by augustss** [comment]
Yes, the macro is `__MHS__`.  But the `containers` package has already been converted to be compilable with mhs.
I don't think it's been uploaded to hackage yet, but the github version should work.

**Comment by augustss** [comment]
Pattern synonyms are coming, btw.

**Comment by treeowl** [comment]
> Yes, the macro is `__MHS__`. But the `containers` package has already been converted to be compilable with mhs. I don't think it's been uploaded to hackage yet, but the github version should work.

I know ... But I didn't see that macro documented. Is there documentation I'm missing? I didn't dig deeply into your compat changes to `containers`, to be honest, and never reviewed the final version.

**Comment by augustss** [comment]
I might not have documented it.  I'll do that.
