### ISSUE TITLE
mhs: error: no location: Not a valid C type: ()

### ISSUE THREAD

**Issue by liolin** [augustss/MicroHs#70]
I'm trying to call C functions that sometimes return nothing / void. In a previous version (commit 2cb9870808f0c9b8996ffc6c148d722d3b89b34c) it worked. Now I get a compiler error:

```
mhs: error: no location: Not a valid C type: ()
```

A minimal example:
```hs
module Blinky(main) where
import Prelude

main :: IO ()
main = c_void_function

foreign import ccall "void_function" c_void_function :: IO ()
```

The following line was added to config-unix-64.h:
```c
void void_function() { /* do stuff here*/ }
```

Could it be due to the changes in commit a537148c15a85c693a55973d84e9f008e69b87f1, where the type `()` was made a built-in type?

**Comment by augustss** [comment]
Fixed in 65a2249a1ba81f0448c0e9f02e9d65d176b88cfd
