### ISSUE TITLE
Type operators rejected in existential type definitions

### ISSUE THREAD

**Issue by treeowl** [augustss/MicroHs#75]
If I write

```haskell
data Fool a b = a ~ b => Fool
```

then I get

```
mhs: error: "Depth.hs": line 18, col 19:
  found:    ~
  expected: LQIdent ( UQIdent [ literal => ⇒ SymOper
```

Note: the same happens if I substitute a plain old class operator for `~`.

If I instead write

```haskell
data Fool a b = (~) a b => Fool
```

then it parses (and compiles) successfully.

**Comment by augustss** [comment]
Yes, there's a bug in parsing contexts. (a ~ b) might work. 

I'll fix the bug in a few days.

**Comment by treeowl** [comment]
Indeed, parentheses work around the problem.

**Comment by augustss** [comment]
I always use parenthesis, so I've not noticed the problem.
