### ISSUE TITLE
Top-level pattern bindings are not supported

### ISSUE THREAD

**Issue by Ei30metry** [augustss/MicroHs#77]
The parser can't handle top-level  pattern bindings such as the following:

```haskell
Just x = fmap (1+) (Just 2)
```

**Comment by augustss** [comment]
Yes, I'm aware of this.  It's an annoying change to make, but I guess I should. :)

**Comment by augustss** [comment]
Fixed in ecebfb40645b15748e4f25c6cbc31fae03e2deb0

**Comment by Ei30metry** [comment]
That was amazingly fast.
